[project]
name = "ag2-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag2[ollama,openai]>=0.9.9",
    "ipykernel>=6.30.1",
    "pip>=25.2",
    "pip-system-certs>=5.2",
]
